Repository GrebbMe/grabbme-fe, pull requests merged in 2024-10, with the labels that each got.

#39 [HOTFIX] 폰트 경로 오타 및 기타 오타 이슈 수정
  src/app/styles/globalStyle.ts
  src/app/styles/typo.ts
  src/shared/consts/routerPath.ts
  src/shared/ui/button/Button.stories.tsx
Labels: bug, hotfix

#45 [FIX] 1차 버튼 컴포넌트 구조 수정
  .storybook/main.ts
  src/app/styles/device.ts
  src/app/styles/globalStyle.ts
  src/app/styles/typo.ts
  src/shared/assets/index.ts
  src/shared/assets/svg/IcBookmark.svg
  src/shared/assets/svg/IcList.svg
  src/shared/types/ButtonProps.ts
  src/shared/ui/button/Button.stories.tsx
  src/shared/ui/button/Button.style.ts
  src/shared/ui/button/Button.tsx
  src/shared/ui/button/button.style.ts
Labels: fix

#48 [FEAT] 토스트 구현
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/app/App.tsx
  src/shared/assets/svg/IcCheckOne.svg
  src/shared/hooks/useToast.ts
  src/shared/index.ts
  src/shared/stores/toastStore.ts
  src/shared/ui/button/Button.stories.tsx
  src/shared/ui/button/Button.tsx
  src/shared/ui/button/CompletedButton.stories.ts
  src/shared/ui/button/CompletedButton.tsx
  src/shared/ui/button/completedButton.style.ts
  src/shared/ui/index.ts
  src/shared/ui/toast/Toast.stories.tsx
  src/shared/ui/toast/Toast.style.ts
  src/shared/ui/toast/Toast.tsx
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: :white_check_mark: feat

#52 [UI] 모달 및 레이아웃 UI
  .storybook/preview.tsx
  src/app/App.tsx
  src/app/layout/Footer.style.ts
  src/app/layout/Footer.tsx
  src/app/layout/Header.style.ts
  src/app/layout/Header.tsx
  src/app/layout/index.ts
  src/app/layout/layout.style.ts
  src/app/styles/globalStyle.ts
  src/features/post/ui/deadlineCalendar/CustomCalendarContainer.tsx
  src/pages/auth/ui/GithubLogin.tsx
  src/shared/assets/image/logo.png
  src/shared/assets/index.ts
  src/shared/assets/svg/IcArrowDown.svg
  src/shared/assets/svg/IcArrowUp.svg
  src/shared/assets/svg/IcLongGithub.svg
  src/shared/assets/svg/IcProfile.svg
  src/shared/assets/svg/IcProgrammers.svg
  src/shared/hooks/useModal.ts
  src/shared/hooks/useOutsideClick.ts
  src/shared/index.ts
  src/shared/stores/modalStore.ts
  src/shared/ui/input/Input.tsx
  src/shared/ui/input/index.ts
  src/shared/ui/modal/Modal.stories.tsx
  src/shared/ui/modal/Modal.style.ts
  src/shared/ui/modal/Modal.tsx
  src/shared/ui/select/MultiSelect.tsx
  src/shared/ui/select/SelectList.stories.tsx
  src/shared/ui/select/SelectList.tsx
  src/shared/ui/textfield/TextField.stories.tsx
  src/shared/ui/textfield/TextField.style.ts
  src/shared/ui/textfield/TextField.tsx
Labels: bug, :white_check_mark: feat, ui

#57 [FIX] 재사용성을 고려한 버튼 컴포넌트 재구성
  src/shared/assets/index.ts
  src/shared/assets/svg/IcChat.svg
  src/shared/assets/svg/IcChatGithub.svg
  src/shared/assets/svg/IcChatStart.svg
  src/shared/assets/svg/IcClose.svg
  src/shared/assets/svg/IcLoginGithub.svg
  src/shared/assets/svg/IcPhoto.svg
  src/shared/assets/svg/IcSend.svg
  src/shared/hooks/useOutsideClick.ts
  src/shared/types/index.ts
  src/shared/ui/button/Button.stories.tsx
  src/shared/ui/button/Button.style.ts
  src/shared/ui/button/Button.tsx
  src/shared/ui/index.ts
  src/shared/ui/modal/Modal.tsx
  src/shared/ui/storybook/story.style.ts
  tsconfig.app.json
Labels: ui, fix

#66 [MOVE] stackbadge 파일 이동
  src/shared/ui/stachBadge/StackBadge.tsx
  src/shared/ui/stachBadge/StackSelectButton.stories.tsx
  src/shared/ui/stachBadge/index.ts
  src/shared/ui/stachBadge/stackBadge.style.ts
Labels: move

#76 [HOTFIX] 버튼 수정 반영
  src/app/layout/Header.tsx
  src/shared/ui/modal/Modal.tsx
Labels: bug, hotfix

#72 [HOTFIX] 모집 기간 UI 컴포넌트 수정
  src/features/post/ui/projectPeriod/PeriodModal.style.ts
  src/features/post/ui/projectPeriod/PeriodModal.tsx
  src/features/post/ui/projectPeriod/ProjectPeriod.stories.tsx
  src/features/post/ui/projectPeriod/ProjectPeriod.style.ts
  src/features/post/ui/projectPeriod/ProjectPeriod.tsx
  src/features/post/ui/projectPeriod/index.ts
Labels: bug, hotfix, ui

#74 [HOTFIX] 모집 마감일 UI 에러 수정
  src/features/post/ui/deadlineCalendar/CustomCalendarContainer.tsx
  src/features/post/ui/deadlineCalendar/DeadlineCalendar.style.ts
  src/features/post/ui/deadlineCalendar/DeadlineCalendar.tsx
Labels: bug, hotfix, ui

#80 [UI] 레이아웃 수정 및 공통 컴포넌트 수정 , 추가
  src/app/layout/Footer.style.ts
  src/app/layout/Header.style.ts
  src/app/layout/Header.tsx
  src/app/layout/Layout.tsx
  src/app/layout/layout.style.ts
  src/app/styles/device.ts
  src/features/post/ui/deadlineCalendar/DeadlineCalendar.style.ts
  src/features/post/ui/projectPeriod/ProjectPeriod.style.ts
  src/shared/assets/index.ts
  src/shared/assets/svg/IcClose.svg
  src/shared/assets/svg/IcSmallChat.svg
  src/shared/assets/svg/IcView.svg
  src/shared/ui/index.ts
  src/shared/ui/modal/Modal.stories.tsx
  src/shared/ui/select/AddButton.style.tsx
  src/shared/ui/select/AddButton.tsx
  src/shared/ui/select/MultiSelect.stories.tsx
  src/shared/ui/select/MultiSelect.style.ts
  src/shared/ui/select/RemoveButton.style.ts
  src/shared/ui/select/RemoveButton.tsx
  src/shared/ui/select/Select.stories.tsx
  src/shared/ui/select/Select.style.ts
  src/shared/ui/tag/Tag.stories.tsx
  src/shared/ui/tag/Tag.style.ts
  src/shared/ui/tag/Tag.tsx
  src/shared/ui/textfield/TextField.stories.tsx
  src/shared/ui/textfield/TextField.style.ts
  src/shared/ui/titleBar/TitleBar.stories.tsx
  src/shared/ui/titleBar/TitleBar.style.ts
  src/shared/ui/toast/Toast.stories.tsx
Labels: ui, fix

#82 [HOTFIX] 사용하지 않는 기타 컴포넌트 및 파일 삭제
  src/app/routers/router.tsx
  src/features/chat/index.ts
  src/features/chat/ui/ChatButton.stories.ts
  src/features/chat/ui/ChatButton.tsx
  src/features/chat/ui/ChatFeatureButton.stories.ts
  src/features/chat/ui/ChatFeatureButton.tsx
  src/features/chat/ui/chatButton.style.ts
  src/features/chat/ui/chatFeatureButton.style.ts
  src/pages/auth/ui/GithubLogin.tsx
  src/pages/auth/ui/index.ts
  src/shared/assets/bookmark.svg
  src/shared/assets/chat-fill.svg
  src/shared/assets/close.svg
  src/shared/assets/github.svg
  src/shared/assets/list-color.svg
  src/shared/assets/photo.svg
  src/shared/assets/send.svg
Labels: hotfix

#85 [TYPO] StackBadge 폴더명 및 파일명 변경
  src/shared/ui/stackBadge/StackBadge.stories.tsx
  src/shared/ui/stackBadge/StackBadge.tsx
  src/shared/ui/stackBadge/index.ts
  src/shared/ui/stackBadge/stackBadge.style.ts
Labels: typo

#89 [UI] Home 진행중인 프로젝트 해더 구현
  src/features/home/lib/monthUtils.ts
  src/features/home/ui/ChartHeader.stories.tsx
  src/features/home/ui/ChartHeader.style.ts
  src/features/home/ui/ChartHeader.tsx
  src/features/home/ui/chartHeader.style.ts
  src/shared/assets/svg/IcArrowNext.svg
  src/shared/assets/svg/IcArrowPrev.svg
  src/shared/assets/svg/index.ts
Labels: ui

#94 [FEAT] RE : 로그인/회원가입 로직 구현 및 퍼블리싱
  src/app/layout/Header.tsx
  src/features/auth/ui/SocialLogin.tsx
  src/pages/auth/api/index.ts
  src/pages/auth/api/registerUser.ts
  src/pages/auth/index.ts
  src/pages/auth/ui/Login.tsx
  src/pages/auth/ui/SignUp.style.ts
  src/pages/auth/ui/SignUp.tsx
  src/pages/auth/ui/index.ts
  src/shared/assets/svg/IcGithubFilled.svg
  src/shared/hooks/useFetchCategories.ts
  src/shared/ui/select/Select.style.ts
  src/shared/ui/select/Select.tsx
  src/shared/util/areAllChecked.ts
  src/shared/util/index.ts
Labels: bug, :white_check_mark: feat, ui, refactor, typo

#87 [UI] top5 stack UI 구현하기
  public/data/topFiveStacks.json
  src/features/home/api/topFiveStacks.api.ts
  src/features/home/model/stack.model.ts
  src/features/home/ui/TopFiveStacks.stories.tsx
  src/features/home/ui/TopFiveStacks.tsx
  src/features/home/ui/topFiveStacks.style.ts
Labels: ui

#91 [UI] 마이페이지 컴포넌트 UI 구현
  src/app/layout/Layout.tsx
  src/app/layout/index.ts
  src/app/routers/router.tsx
  src/app/styles/color.ts
  src/entities/myPage/consts/statusLabelMap.ts
  src/entities/myPage/index.ts
  src/entities/myPage/ui/StatusTag.stories.tsx
  src/entities/myPage/ui/StatusTag.style.ts
  src/entities/myPage/ui/StatusTag.tsx
  src/features/contentCard/ContentCard.stories.tsx
  src/features/contentCard/ContentCard.style.ts
  src/features/contentCard/ContentCard.tsx
  src/features/index.ts
  src/features/myPage/index.ts
  src/features/myPage/ui/Sidebar.stories.tsx
  src/features/myPage/ui/Sidebar.style.ts
  src/features/myPage/ui/Sidebar.tsx
  src/features/statusCard/StatusCard.stories.tsx
  src/features/statusCard/StatusCard.style.ts
  src/features/statusCard/StatusCard.tsx
  src/pages/mypage/index.ts
  src/pages/mypage/ui/MyBookmarks.tsx
  src/pages/mypage/ui/MyPosts.tsx
  src/pages/mypage/ui/MyProfile.tsx
  src/pages/mypage/ui/MyProjects.tsx
  src/shared/assets/index.ts
  src/shared/assets/svg/IcBookmarkSmall.svg
  src/shared/assets/svg/IcChatSmall.svg
  src/shared/assets/svg/IcViewSmall.svg
  src/shared/consts/routerPath.ts
  src/shared/types/index.ts
  src/shared/types/status.ts
  src/shared/ui/countLabel/CountLabel.stories.tsx
  src/shared/ui/countLabel/CountLabel.style.ts
  src/shared/ui/countLabel/CountLabel.tsx
  src/shared/ui/index.ts
Labels: ui

#105 [TYPO] : 스타일 파일명 변경
  src/features/home/ui/ChartHeader.tsx
  src/features/home/ui/TopFiveStacks.style.ts
  src/features/home/ui/TopFiveStacks.tsx
Labels: typo

#97 [UI] 채팅 컴포넌트 UI 구현
  src/app/App.tsx
  src/app/styles/color.ts
  src/entities/chat/index.ts
  src/entities/chat/ui/FloatingButton.style.ts
  src/entities/chat/ui/FloatingButton.tsx
  src/features/chat/index.ts
  src/features/chat/ui/ChatInput.stories.tsx
  src/features/chat/ui/ChatInput.style.ts
  src/features/chat/ui/ChatInput.tsx
  src/features/chat/ui/ChatMessage.stories.tsx
  src/features/chat/ui/ChatMessage.style.ts
  src/features/chat/ui/ChatMessage.tsx
  src/features/chat/ui/ChatPreview.stories.tsx
  src/features/chat/ui/ChatPreview.style.ts
  src/features/chat/ui/ChatPreview.tsx
  src/shared/assets/index.ts
  src/shared/assets/svg/IcBack.svg
  src/shared/assets/svg/IcClose.svg
  src/shared/assets/svg/IcDefaultProfile.svg
  src/shared/assets/svg/IcSendActive.svg
  src/shared/index.ts
  src/shared/lib/truncateText.ts
  src/shared/stores/chatNavigationStore.ts
  src/widgets/chat/index.ts
  src/widgets/chat/lib/sortChatRooms.ts
  src/widgets/chat/ui/ChatRoom.stories.tsx
  src/widgets/chat/ui/ChatRoom.style.ts
  src/widgets/chat/ui/ChatRoom.tsx
  src/widgets/chat/ui/ChatRoomList.stories.tsx
  src/widgets/chat/ui/ChatRoomList.style.ts
  src/widgets/chat/ui/ChatRoomList.tsx
  src/widgets/chat/ui/ChatSection.style.ts
  src/widgets/chat/ui/ChatSection.tsx
Labels: ui

#101 [UI] 검색 UI 구현
  src/features/home/assets/IcSubmit.svg
  src/features/home/assets/index.ts
  src/features/home/ui/Search.stories.tsx
  src/features/home/ui/Search.style.ts
  src/features/home/ui/Search.tsx
Labels: ui

#110 [PACKAGE] axios 패키지 추가
  package-lock.json
  package.json
Labels: package

#96 [UI] 홈페이지 진행중인 프로젝트 sidebar 구현
  src/features/home/ui/ChartSidebar.stories.tsx
  src/features/home/ui/ChartSidebar.style.ts
  src/features/home/ui/ChartSidebar.tsx
Labels: ui

#103 [UI] 곧 마감되는 프로젝트 카드 UI 구현
  src/features/home/ui/ClosingProject.stories.tsx
  src/features/home/ui/ClosingProject.style.ts
  src/features/home/ui/ClosingProject.tsx
Labels: ui

#104 [UI] 버블 차트 구현
  package-lock.json
  package.json
  src/features/home/ui/BubbleChart.stories.tsx
  src/features/home/ui/BubbleChart.style.ts
  src/features/home/ui/BubbleChart.tsx
Labels: ui

#90 [UI] 검색바 ,스택 검색 UI
  .storybook/preview.tsx
  src/app/layout/Header.tsx
  src/app/layout/layout.style.ts
  src/app/routers/router.tsx
  src/features/board/hooks/useSearch.ts
  src/features/board/hooks/useStackSearch.ts
  src/features/board/ui/search/searchBar/SearchBar.stories.tsx
  src/features/board/ui/search/searchBar/SearchBar.style.ts
  src/features/board/ui/search/searchBar/SearchBar.tsx
  src/features/board/ui/search/stackSearch/StackSearch.stories.tsx
  src/features/board/ui/search/stackSearch/StackSearch.style.ts
  src/features/board/ui/search/stackSearch/StackSearch.tsx
  src/pages/post/grabbzone/GrabbZone.tsx
  src/pages/post/index.ts
  src/pages/post/project/Project.tsx
  src/shared/assets/index.ts
  src/shared/assets/svg/IcSearch.svg
  src/shared/consts/routerPath.ts
  src/shared/ui/countBox/CountBox.stories.tsx
  src/shared/ui/countBox/CountBox.style.ts
  src/shared/ui/countBox/CountBox.tsx
Labels: :white_check_mark: feat, ui

#113 프로젝트와 그렙존 게시글 상세 페이지 1차 구현
  package-lock.json
  src/app/routers/router.tsx
  src/pages/post/grabbzone/GrabbZoneDetail.style.ts
  src/pages/post/grabbzone/GrabbZoneDetail.tsx
  src/pages/post/index.ts
  src/pages/post/project/ProjectDetail.style.ts
  src/pages/post/project/ProjectDetail.tsx
  src/shared/consts/routerPath.ts
  src/shared/ui/progressBar/ProgressBar.stories.tsx
  src/shared/ui/progressBar/ProgressBar.style.ts
  src/shared/ui/progressBar/ProgressBar.tsx
Labels: :white_check_mark: feat, ui

#119 [UI] 랜딩 페이지 구현
  src/app/layout/Layout.tsx
  src/app/layout/layout.style.ts
  src/app/routers/router.tsx
  src/features/home/index.ts
  src/features/home/ui/ChartSidebar.tsx
  src/pages/home/ui/Home.style.ts
  src/pages/home/ui/Home.tsx
  src/shared/consts/routerPath.ts
  src/shared/ui/stackBadge/index.ts
  src/widgets/home/index.ts
  src/widgets/home/model/stack.model.ts
  src/widgets/home/ui/AllClosingProject.style.ts
  src/widgets/home/ui/AllClosingProject.tsx
  src/widgets/home/ui/AllStackBadge.style.ts
  src/widgets/home/ui/AllStackBadge.tsx
  src/widgets/home/ui/BubbleBox.tsx
  src/widgets/home/ui/Chart.style.ts
  src/widgets/home/ui/Chart.tsx
  src/widgets/home/ui/ChartBox.style.ts
  src/widgets/home/ui/LineGraphBox.tsx
  src/widgets/home/ui/RecentHotProject.style.ts
  src/widgets/home/ui/RecentHotProject.tsx
Labels: ui

#132 [Feat] 마이페이지 데이터 패칭
  src/app/routers/router.tsx
  src/entities/myPage/index.ts
  src/entities/myPage/ui/ContentTag.stories.tsx
  src/entities/myPage/ui/ContentTag.style.ts
  src/entities/myPage/ui/ContentTag.tsx
  src/features/myPage/api/getUserProfile.ts
  src/features/myPage/hooks/useUserProfile.ts
  src/features/myPage/index.ts
  src/features/myPage/model/UserProfileResponse.ts
  src/features/user/api/getProjectCategoryById.ts
  src/features/user/api/getStackCategoryById.ts
  src/features/user/hooks/useProjectCategoryNames.ts
  src/features/user/hooks/useStackCategoryNames.ts
  src/pages/mypage/index.ts
  src/pages/mypage/ui/MyBookmarkPage.tsx
  src/pages/mypage/ui/MyBookmarks.tsx
  src/pages/mypage/ui/MyPostPage.tsx
  src/pages/mypage/ui/MyPosts.tsx
  src/pages/mypage/ui/MyProfile.tsx
  src/pages/mypage/ui/MyProfilePage.style.ts
  src/pages/mypage/ui/MyProfilePage.tsx
  src/pages/mypage/ui/MyProjectPage.tsx
  src/pages/mypage/ui/MyProjects.tsx
  src/shared/api/axiosInstance.ts
  src/widgets/user/index.ts
  src/widgets/user/ui/ProfileDetail.stories.tsx
  src/widgets/user/ui/ProfileDetail.style.ts
  src/widgets/user/ui/ProfileDetail.tsx
  src/widgets/user/ui/UserProfile.stories.tsx
  src/widgets/user/ui/UserProfile.style.ts
  src/widgets/user/ui/UserProfile.tsx
Labels: :white_check_mark: feat
