Repository GrebbMe/grabbme-fe, pull requests merged in 2024-09, with the labels that each got.

#2 [CHORE] 프로젝트 초기설정
  .eslintignore
  .eslintrc.json
  .gitattributes
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  .prettierrc
  README.md
  index.html
  jest.config.js
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ⚙️ chore, 📃docs

#15 [CHORE] 맥 유저를 위한 husky 파일 실행 권한 설정 업데이트
  .husky/commit-msg
  .husky/pre-commit
Labels: ⚙️ chore

#19 [CHORE] FSD 아키텍처를 적용하여 폴더 구조를 변경
  src/App.css
  src/app/App.tsx
  src/app/layout/index.ts
  src/app/providers/index.ts
  src/app/routers/index.ts
  src/app/styles/index.ts
  src/app/types/index.ts
  src/entities/auth/index.ts
  src/entities/chat/index.ts
  src/entities/post/index.ts
  src/entities/user/index.ts
  src/features/auth/index.ts
  src/features/auth/ui/SocialLogin.tsx
  src/features/chat/index.ts
  src/features/post/index.ts
  src/features/user/index.ts
  src/main.tsx
  src/pages/auth/index.ts
  src/pages/auth/ui/Login.tsx
  src/pages/auth/ui/SignUp.tsx
  src/pages/chat/index.ts
  src/pages/post/index.ts
  src/pages/user/index.ts
  src/shared/api/index.ts
  src/shared/assets/react.svg
  src/shared/consts/index.ts
  src/shared/types/index.ts
  src/shared/ui/button/Button.tsx
  src/shared/ui/button/index.ts
  src/shared/ui/dropDown/DropDown.tsx
  src/shared/ui/dropDown/index.ts
  src/shared/ui/input/Input.tsx
  src/shared/ui/input/index.ts
  src/widgets/auth/index.ts
  src/widgets/auth/ui/LoginForm.tsx
  src/widgets/auth/ui/SignUpForm.tsx
  src/widgets/chat/index.ts
  src/widgets/post/index.ts
  src/widgets/user/index.ts
Labels: ⚙️ chore

#18 [CHORE] 디자인 시스템 및 라우팅 초기 설정
  .eslintrc.json
  package-lock.json
  package.json
  src/app/App.tsx
  src/app/layout/Footer.tsx
  src/app/layout/Header.tsx
  src/app/layout/Layout.tsx
  src/app/layout/index.ts
  src/app/layout/layout.style.ts
  src/app/routers/index.ts
  src/app/routers/router.tsx
  src/app/styles/color.ts
  src/app/styles/device.ts
  src/app/styles/globalStyle.ts
  src/app/styles/index.ts
  src/app/styles/styled.d.ts
  src/app/styles/theme.ts
  src/app/styles/typo.ts
  src/features/index.ts
  src/index.css
  src/main.tsx
  src/pages/auth/ui/GithubLogin.tsx
  src/pages/auth/ui/index.ts
  src/shared/assets/font/PretendardVariable.woff2
  src/shared/consts/rotuerPath.ts
  src/shared/index.ts
  vite.config.ts
Labels: ⚙️ chore

#26 [HOTFIX] import 문 수정
  src/main.tsx
Labels: bug

#28 [HOTFIX] 폰트 파일 변경
  src/app/styles/globalStyle.ts
  src/app/styles/index.ts
  src/shared/assets/font/Pretendard-Medium.woff2
  src/shared/assets/font/Pretendard-Regular.woff2
  src/shared/assets/font/Pretendard-SemiBold.woff2
  src/shared/assets/font/PretendardVariable.woff2
  src/shared/index.ts
Labels: bug, ⚙️ chore

#29 [Chore] Storybook 기본 설정 및 테스트 자동화
  .eslintrc.json
  .github/workflows/storybook.yml
  .storybook/main.ts
  .storybook/preview-head.html
  .storybook/preview.tsx
  package-lock.json
  package.json
  public/assets/font/Pretendard-Medium.woff2
  public/assets/font/Pretendard-Regular.woff2
  public/assets/font/Pretendard-SemiBold.woff2
  src/app/App.tsx
  src/app/layout/Layout.tsx
  src/app/layout/index.ts
  src/app/routers/router.tsx
  src/app/styles/globalStyle.ts
  src/app/styles/theme.ts
  src/main.tsx
  src/shared/index.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  vite.config.ts
Labels: ⚙️ chore

#34 [HOTFIX] 로컬에서 스토리북이 빌드되지 않는 현상
  .github/PULL_REQUEST_TEMPLATE.md
  .storybook/main.ts
Labels: bug, hotfix
